version: "3"
services:

    redis:
        image: redis:alpine
        ports:
            - "6379"
        networks:
            - frontend
    db:
        image: postgres:9.4
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
    vote:
        image: boathousex/voting-vote:latest
        ports:
            - 5000:80
        networks:
            - frontend
        depends_on:
            - redis
    result:
        image: boathousex/voting-result:latest
        ports:
            - 5001:80
        networks:
            - backend
        depends_on:
            - db

    worker:
        image: boathousex/voting-worker:latest
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:

volumes:
    db-data:
