version: '3'

services:
  vote:
    image: vote
    build:
      context: ./vote
      dockerfile: Dockerfile
  result:
    image: result
    build:
      context: ./result
      dockerfile: Dockerfile
  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
  redis:
    image: redis:alpine
  db:
    image: postgres:9.4