version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    image: boat-house-vote:latest
    container_name: boat-house_vote
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier

  result:
    build: ./result
    command: node --inspect server.js
    image: boat-house-result:latest
    container_name: boat-house_result
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - back-tier

  worker:
    build: ./worker
    image: boat-house-worker:latest
    container_name: boat-house_worker
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - front-tier

  db:
    image: postgres:9.6-alpine
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
